### ISSUE TITLE
Dropboxのファイルが表示されない

### ISSUE THREAD

**Issue by YosAwed** [asaday/MDXPlayer#4]
masterブランチからコンパイルして使わせていただいているのですが、dropboxからのリスト表示が出てきません。
forkしてDropboxClientsManager.authorizeFromControllerV2に変えてみたのですが、状況変わらずでした。以下はログです。空のリストが返ってきているようです。

Success! User is logged into DropboxClientsManager.
/var/mobile/Containers/Data/Application/10E35664-3114-4558-BDB0-66D52C592020/Library/Caches/_dropbox_
_dropbox_
(
)
(
)

**Comment by asaday** [comment]
DropBoxについては [SwiftyDropbox](https://github.com/dropbox/SwiftyDropbox) を追って頂いた方がよさそうですが
現在masterにあるPodfile.lock の記載では version 6.0.3 を使用しております。
念の為別途cloneして起動してみましたが無事にログイン＆取得が出来ております。

**Comment by YosAwed** [comment]
返信ありがとうございます。
ふと思って、今ストアにあるものに入れ直してみたところ正常にリストが取れました。(以前取れなかったので、自分でコンパイルしたというのが取っ掛かり)
こちらのSwiftDropboxとAlamofireのせいっぽいですね。クローズいただいて大丈夫です。ありがとうございました。
